Update ivoatex and remove aap citation workaround
ivoa-std/VOTable pull request #43
Opened 2023-09-08 20:29 UTC by tomdonaldson

With the[ ivoatex fix for ADS-defined macros](https://github.com/ivoa-std/ivoatex/issues/119), we no longer need the workaround to allow bib references to `\aas'.  This updates the ivoatex to the latest and removes that workaround.

2023-09-11 07:31 UTC, msdemlei requested changes
First, as said in the recent ivoatexDoc change, don't use ampersands in bibitems (2015A&A...574A..36R), as they'll break HTML output.  But then the Rots et al paper on times is in the ivoatex/ivoabib.bib anyway; just drop your bibrecord and use \citep{2015A+A...574A..36R}.

2023-09-11 14:16 UTC, tomdonaldson commented
> First, as said in the recent ivoatexDoc change, don't use ampersands in bibitems (2015A&A...574A..36R), as they'll break HTML output. But then the Rots et al paper on times is in the ivoatex/ivoabib.bib anyway; just drop your bibrecord and use \citep{2015A+A...574A..36R}.

I guess I was hoping that although there are errors mentioned when making the html, that the output html product seems OK to me.

Errors during make:
```
-:1181: HTML parser error : htmlParseEntityRef: expecting ';'
	<a href="#2015A&A...574A..36R" id="CITE2015A&A...574A..36R" class="tth_citation
	                             ^
-:1181: HTML parser error : htmlParseEntityRef: expecting ';'
	<a href="#2015A&A...574A..36R" id="CITE2015A&A...574A..36R" class="tth_citation
	                                                          ^
.
.
.
-:3755: HTML parser error : htmlParseEntityRef: expecting ';'
  <a name='2015A&A...574A..36R'/>
                              ^
```

But in the output html, those are all escaped:
```
        <a href="#2015A&amp;A...574A..36R" id="CITE2015A&amp;A...574A..36R" class="tth_citation">
        (Rots and Bunclark et al., 2015)</a>.</dd>
 <dt><b><tt><span style="color:#7F0000">timescale</span></tt></b></dt>
.
.
.
  <a name="2015A&amp;A...574A..36R"/>
  </dd> 
 <dt><b>Rots &amp; Bunclark et al. (2015)</b></dt>
        <dd>  
Rots, A. H., Bunclark, P. S., Calabretta, M. R., Allen, S. L.,
  Manchester, R. N. &amp; Thompson, W. T.  (
2015), `Representations of time coordinates in FITS. Time
  and relative dimension in space', <em><span class="roman">A&amp;A</span></em> <b>574</b>, A36,
  arXiv:1409.7583.
```

Do the errors negatively impact the make or the output other than the error messages?  I just want to make sure since I find changing the bibcode potentially confusing and it's probably easy for others to miss this needed substitution.

2023-09-11 14:28 UTC, tomdonaldson commented
> ... just drop your bibrecord ...
Sorry for the ignorance, but specifically what does this mean?

2023-09-12 07:38 UTC, msdemlei commented
On Mon, Sep 11, 2023 at 07:16:21AM -0700, Tom wrote:
> I guess I was hoping that although there are errors mentioned when
> making the html, that the output html product seems OK to me.
>
> Errors during make:
> ```
> -:1181: HTML parser error : htmlParseEntityRef: expecting ';'
> 	<a href="#2015A&A...574A..36R" id="CITE2015A&A...574A..36R" class="tth_citation

I have to admit I have not investigated more closely, but from what
your messages what happens is that xsltproc (which ivoatex is using
to clean up tth's output and do some extra tricks) is lenient enough
to accept the malformed HTML and translate it to well-formed XML, as
evinced by:

>         <a href="#2015A&amp;A...574A..36R" id="CITE2015A&amp;A...574A..36R" class="tth_citation">
>         (Rots and Bunclark et al., 2015)</a>.</dd>
>  <dt><b><tt><span style="color:#7F0000">timescale</span></tt></b></dt>

But really, this isn't behaviour I want to count on, even though
there's lots of legacy HTML that shares this problem (<a
href="/script?a=b&c=d"> -- yes, that's malformed HTML).  Either we fix
tth or we avoid ampersands in bibliography labels.

> Do the errors negatively impact the make or the output other than
> the error messages?  I just want to make sure since I find changing
> the bibcode potentially confusing and it's probably easy for others
> to miss this needed substitution.

I give you it's not overly pretty, but then you don't add
bibliography items every day in IVOA standards.  If it's too much
hassle on the long run, I'll bite the bullet and fix tth (or someone
else does), but I'd rather wait; if I just have to write one PR
comment per year, it's probably a deal for me.

2023-09-12 07:38 UTC, msdemlei commented
On Mon, Sep 11, 2023 at 07:29:05AM -0700, Tom wrote:
> > ... just drop your bibrecord ...
>
> Sorry for the ignorance, but specifically what does this mean?

Oh, what I wanted to say is "remove the record starting with
***@***.***{2015A&A...574A..36R' from localrefs.bib and use
\citep{2015A+A...574A..36R} in VOTable.tex, which takes the record
from ivoabib.bib".

Sorry for being overly terse.

2023-09-12 18:45 UTC, tomdonaldson commented
Thanks for your patience @msdemlei.  I understand much better now, and think this is ready to go.

2023-09-12 19:04 UTC, merged