Updates based on RFC comments
ivoa-std/VOTable pull request #62
Opened 2024-11-16 10:49 UTC by tomdonaldson

This contains several small additions and clarifications based on RFC comments to date:

- Added MIVOT to the architecture diagram
- Added a sentence to clarify the (non)advice for ordering of `ID` and `ref` attributes.
- Adopted suggestion to calling out the equivalence of ET and TT `timescale`
- Clarified that MIVOT elements are allowed with the VOTable schema.
- Adopted suggested wording change about the use of `type="meta"` for a MIVOT `RESOURCE`.

2024-11-18 14:55 UTC, mbtaylor requested changes
Looks fine apart from one comment.

2024-11-18 14:55 UTC, mbtaylor commented on VOTable.tex
> +and any valid XML, in a \elem{RESOURCE}.
This should say something like  _"and any elements from a foreign namespace"_  not _"and any valid XML"_ here.  Non-VOTable elements in the VOTable namespace are not allowed.

2024-11-19 09:32 UTC, gmantele commented
> * Added a sentence to clarify the (non)advice for ordering of `ID` and `ref` attributes.

I am fine with the added clarification about this second point. Thank you :slightly_smiling_face:

2024-11-22 22:47 UTC, mbtaylor approved these changes

2024-11-25 01:44 UTC, merged